name: Sprint Start

on:
  schedule:
    - cron: "0 8 * * 2"

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - run: npm start
        env:
          mode: sprint_start
